-- phpMyAdmin SQL Dump
-- version 5.2.1
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Jan 29, 2024 at 12:16 PM
-- Server version: 10.4.28-MariaDB
-- PHP Version: 8.2.4

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `db_recipe`
--

-- --------------------------------------------------------

--
-- Table structure for table `admininfo`
--

CREATE TABLE `admininfo` (
  `adminID` varchar(100) NOT NULL,
  `adminFirstName` varchar(100) NOT NULL,
  `adminLastName` varchar(100) NOT NULL,
  `adminEmail` varchar(100) NOT NULL,
  `adminPassword` varchar(100) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `admininfo`
--

INSERT INTO `admininfo` (`adminID`, `adminFirstName`, `adminLastName`, `adminEmail`, `adminPassword`) VALUES
('LD-23-01', 'Lourdes', 'Sebastian', 'Lourdes@gmail.com', 'LS123!?*');

-- --------------------------------------------------------

--
-- Table structure for table `foodinfo`
--

CREATE TABLE `foodinfo` (
  `foodID` varchar(100) NOT NULL,
  `foodName` varchar(100) NOT NULL,
  `foodDescription` longtext NOT NULL,
  `foodRecipe` longtext NOT NULL,
  `foodHealthBenefit` longtext NOT NULL,
  `foodProcedure` longtext NOT NULL,
  `foodLink` varchar(1000) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `foodinfo`
--

INSERT INTO `foodinfo` (`foodID`, `foodName`, `foodDescription`, `foodRecipe`, `foodHealthBenefit`, `foodProcedure`, `foodLink`) VALUES
('MN-1', 'Lumpiang Shanghai', 'Lumpiang Shanghai is a popular Filipino dish consisting of small, deep-fried spring rolls filled with a seasoned mixture of ground pork or beef. These bite-sized delights are often served as appetizers, party snacks, or as accompaniments to rice meals. The name \"Shanghai\" suggests a Chinese influence, reflecting the historical ties between Filipino and Chinese cuisine.\nOriginating from Chinese cuisine, Lumpiang Shanghai is a Filipino spring roll filled with ground meat, vegetables, and spices. It reflects the influence of Chinese culinary traditions in Filipino cooking, adapted and embraced over centuries of cultural exchange.', 'Ground pork or beef\nGarlic, minced\nOnion, finely chopped\nCarrots, grated\nGreen onions, chopped\nSoy sauce\nSalt and pepper to taste\nLumpia wrappers (spring roll wrappers)\nCooking oil for frying\nEgg, beaten (for sealing)', 'Protein Source: The ground pork or beef in Lumpiang Shanghai provides a good source of protein, essential for muscle growth and repair.\nVegetable Inclusion: The addition of vegetables like onions and carrots contributes vitamins, minerals, and fiber to the dish.\nCustomizable: You can modify the recipe to include more vegetables or use leaner meat for a healthier option.\nModeration is Key: While Lumpiang Shanghai is delicious, it\'s important to enjoy it in moderation due to its fried nature, which can contribute to higher calorie and fat content.\nSocial and Cultural Aspect: Beyond its nutritional aspects, enjoying Lumpiang Shanghai in a social setting or during cultural events adds to its overall positive impact on well-being.', 'Prepare the Filling: In a bowl, combine ground pork or beef, minced garlic, chopped onions, grated carrots, and chopped green onions. Season the mixture with soy sauce, salt, and pepper. Mix thoroughly.\nAssemble the Lumpia: Take a lumpia wrapper and place a small amount of the filling along one edge. Roll the wrapper tightly over the filling, folding the sides in as you go. Seal the edge with beaten egg to secure the roll.\nRepeat the Process: Continue filling and rolling the lumpia until all the wrappers are used.\nDeep Fry: Heat cooking oil in a pan for deep frying. Fry the lumpia in batches until golden brown and crispy. Place on paper towels to drain excess oil.\nServe: Serve Lumpiang Shanghai hot with a dipping sauce, such as sweet and sour sauce or a vinegar-based dip.', 'https://youtu.be/BIarUjm4U-0?si=NNFPSzGoWY0vbap3'),
('MN-10', 'Kwek-Kwek', 'Kwek-Kwek is a popular Filipino street food made of quail eggs coated in a distinctive orange batter, deep-fried until crispy. The vibrant color of the batter and the small size of the quail eggs make this dish visually appealing. Kwek-Kwek is typically served with a vinegar-based dipping sauce. It exemplifies the creative and accessible nature of Filipino street cuisine.', 'Quail eggs, hard-boiled and peeled\r\nOrange food coloring (achuete or annatto extract can be used for a natural option)\r\nAll-purpose flour\r\nCornstarch\r\nBaking powder\r\nSalt and pepper to taste\r\nWater\r\nCooking oil for deep frying', 'Rich in Protein: Quail eggs are a good source of protein, essential for muscle development, repair, and overall body function.\r\nNutrient Content: Quail eggs contain various vitamins and minerals, including B-vitamins, vitamin A, iron, and zinc, contributing to overall health.\r\nPortion Control: The small size of quail eggs makes kwek-kwek a snack that allows for easy portion control.\r\nCustomizable Batter: By controlling the ingredients in the batter, you can make adjustments to suit dietary preferences, such as using whole-grain flour or reducing salt content.\r\nEconomical: Quail eggs are relatively affordable, making kwek-kwek a budget-friendly treat.', 'Prepare the Batter: In a bowl, mix all-purpose flour, cornstarch, baking powder, salt, and pepper. Add water gradually while stirring until you achieve a smooth, lump-free batter. Add orange food coloring or achuete/annatto extract until the desired color is achieved.\r\nCoat the Quail Eggs: Dip each hard-boiled quail egg into the batter, making sure it\'s evenly coated.\r\nDeep-Fry the Quail Eggs: Heat cooking oil in a deep pan or fryer. Carefully drop the coated quail eggs into the hot oil. Fry until the batter becomes crispy and golden brown. Use a slotted spoon to remove the kwek-kwek from the oil and place them on paper towels to absorb excess oil.\r\nServe: Arrange the kwek-kwek on a serving plate. Serve with a vinegar-based dipping sauce, often mixed with garlic, onions, and red pepper for added flavor.', 'https://www.youtube.com/\r\nwatch?v=PcOIom1tEE8&pp\r\n=ygUJS3dlay1Ld2Vr '),
('MN-11', 'Chicken Adobo', 'Chicken Adobo is a popular Filipino dish known for its savory and slightly tangy flavor. A dish with roots in pre-colonial Philippines, Chicken Adobo involves marinating meat in vinegar, soy sauce, and spices, reflecting the influence of indigenous cooking methods. This dish is cherished for its simplicity, yet it delivers a rich and delicious taste that appeals to many.\n\n', 'Chicken, cut into serving pieces\r\nOnion, peeled and sliced thinly\r\nGarlic, peeled and minced\r\nSoy sauce\r\nVinegar\r\nPeppercorns\r\nBay leaves\r\nWater\r\nCooking oil', 'Protein Source: Chicken is a lean protein source essential for muscle growth and repair.\r\nGarlic: Known for its anti-inflammatory and immune-boosting properties.\r\nSoy Sauce: Contains protein and iron, and adds a rich flavor to the dish.\r\nVinegar: May aid digestion and help control blood sugar levels.\r\nPeppercorns: Contains antioxidants and may have anti-inflammatory properties.\r\nBay Leaves: Rich in vitamins and minerals, known for their antioxidant properties.\r\nWhile Chicken Adobo is a flavorful and satisfying dish, it\'s important to consume it in moderation due to its soy sauce and salt content. Adjusting the recipe to include more vegetables or using a reduced-sodium soy sauce can make it a healthier option.', 'In a bowl, marinate the chicken in soy sauce, garlic, and peppercorns for about 30 minutes.\r\nHeat oil in a pan over medium heat. Add onions and cook until translucent.\r\nAdd the marinated chicken to the pan. Cook until the chicken is browned.\r\nPour in the vinegar and allow it to boil, then simmer for 2 minutes.\r\nAdd water, bay leaves, and let it simmer until the chicken is tender.\r\nSeason with salt and pepper to taste.\r\nServe hot over steamed rice.', 'https://www.youtube.com/\r\nwatch?v=wwapBsT0oc8&pp\r\n=ygUNQ2hpY2tlbiBBZG9ibw\r\n%3D%3D'),
('MN-12', 'Dinuguan', 'Dinuguan is a Filipino savory stew known for its dark, rich, and flavorful broth made from pork blood. Commonly referred to as \"chocolate meat,\" this dish consists of pork meat, internal organs, and sometimes pork skin, simmered in a mixture of pig\'s blood, vinegar, and various spices. A savory pork blood stew demonstrates Filipino resourcefulness in utilizing all parts of the animal. Its roots trace back to pre-colonial indigenous practices. It is a unique and traditional Filipino dish often served with rice or rice cakes.\n\nNote: Some people may find the idea of consuming pork blood unappealing. However, dinuguan is a traditional dish many enjoy, and its unique flavor profile is a significant part of Filipino culinary heritage.', 'Pork belly, diced\r\nPork intestines, cleaned and diced (optional)\r\nPork liver, diced\r\nPork blood\r\nOnion, peeled and chopped\r\nCloves garlic, minced\r\nTablespoons oil\r\nTablespoons vinegar\r\nBay leaves\r\nSalt and pepper to taste\r\nRed chili peppers (optional, for added heat)', 'Protein: Dinuguan provides a good source of protein from pork meat and liver, essential for muscle development and overall body function.\r\nIron: Pork blood is rich in iron, which is crucial for the production of red blood cells and oxygen transport in the body.\r\nVitamins and Minerals: Pork liver contributes essential vitamins and minerals, including vitamin A, vitamin B12, and zinc.\r\nSpices: Ingredients like garlic and onions provide additional health benefits, such as anti-inflammatory and immune-boosting properties.\r\nModeration: While dinuguan has nutritional benefits, it\'s important to consume it in moderation due to its high-fat content and cholesterol levels.', 'Heat oil in a pot over medium heat. Sauté garlic and onions until fragrant.\r\nAdd pork belly and cook until browned. If using pork intestines, add them at this point and cook until slightly tender.\r\nPour in vinegar and allow it to boil for a few minutes.\r\nAdd pork blood, stirring continuously to prevent clotting. Continue to simmer for about 10 minutes.\r\nAdd pork liver and cook until cooked through.\r\nSeason with salt, pepper, and add bay leaves. If desired, add red chili peppers for heat.\r\nSimmer until the broth thickens and the flavors meld.\r\nAdjust seasoning as needed and serve hot.', 'https://www.youtube.com/\r\nwatch?v=lODJmwPtdBo&pp\r\n=ygUIRGludWd1YW4%3D '),
('MN-13', 'Binagoongan', 'Binagoongan is a Filipino dish known for its bold and savory flavors. It typically features pork or beef cooked in bagoong (fermented shrimp paste), garlic, onions, tomatoes, and chili peppers. The dish has a distinct umami taste and is often enjoyed with steamed rice. Binagoongan showcases the Filipino adaptation of flavors brought by early Chinese and Malay traders.\n', 'Pork belly, diced\r\nTablespoons bagoong (fermented shrimp paste)\r\nOnion, chopped\r\nCloves garlic, minced\r\nTomatoes, chopped\r\nRed or green chili peppers (siling labuyo), chopped (adjust to taste)\r\nTablespoon cooking oil\r\nVinegar\r\nWater\r\nSugar and pepper to taste', 'Protein: Pork provides a good source of protein necessary for muscle health.\r\nShrimp Paste (Bagoong): Rich in umami flavor, but should be consumed in moderation due to its salt content. It also contains essential amino acids.\r\nGarlic and Onions: Known for their potential health benefits, including anti-inflammatory and immune-boosting properties.\r\nTomatoes: High in vitamins C and A, as well as antioxidants.\r\nChili Peppers: Contains capsaicin, which may boost metabolism and has potential anti-inflammatory properties.\r\nVinegar: May have digestive benefits and could help stabilize blood sugar levels.\r\nWhile Binagoongan can be a flavorful and satisfying dish, it\'s important to be mindful of the salt content in bagoong. As with any dish, moderation and balance are key to enjoying it as part of a healthy diet.', 'Heat oil in a pan over medium heat. Sauté garlic until golden brown.\r\nAdd onions and cook until translucent.\r\nAdd tomatoes and cook until softened.\r\nAdd pork and cook until browned.\r\nStir in bagoong and cook for a few minutes.\r\nPour in vinegar and let it simmer for about 2 minutes.\r\nAdd water and chili peppers. Simmer until the pork is tender.\r\nSeason with sugar and pepper to balance the flavors.\r\nContinue simmering until the sauce thickens.\r\nAdjust seasoning if needed. Serve hot with steamed rice.', 'https://www.youtube.com/\r\nwatch?v=V5PKKCA12x4&pp\r\n=ygULQmluYWdvb25nYW4%3D '),
('MN-14', 'Kare-Kare', 'Kare-Kare is a traditional Filipino oxtail stew characterized by its rich peanut sauce. It often includes a variety of meats such as oxtail, tripe, and pork hocks, along with vegetables like banana hearts and string beans. The dish is known for its creamy, savory, and slightly sweet flavor, making it a favorite in Filipino cuisine. The dish reflects the Spanish-era Manila aristocracy\'s love for rich, savory dishes.', 'Oxtail, cut into 2-inch pieces\r\nTripe, cleaned and sliced\r\nPork hocks\r\nPeanut butter\r\nOnion, peeled and sliced\r\nGarlic, peeled and minced\r\nEggplants, sliced\r\nBanana hearts (puso ng saging), sliced\r\nString beans (sitaw), cut into 2-inch lengths\r\nAnnatto seeds (achuete)\r\nCooking oil\r\nSalt and pepper to taste', 'Oxtail and Tripe: Good sources of protein, iron, and other essential nutrients.\r\nPeanut Butter: Provides healthy fats, protein, and important vitamins and minerals.\r\nVegetables: Eggplants, banana hearts, and string beans add fiber, vitamins, and minerals to the dish.\r\nAnnatto Seeds: May have antioxidant and anti-inflammatory properties.\r\nGarlic and Onions: Known for their potential health benefits, including immune support and anti-inflammatory effects.\r\nWhile Kare-Kare is a flavorful and hearty dish, it\'s worth noting that it can be high in calories and fat due to the peanut sauce. As with any dish, moderation is key, and you can make adjustments to suit your dietary preferences, such as using leaner cuts of meat or reducing the amount of peanut butter.', 'Boil oxtail, tripe, and pork hocks in a large pot until tender. Remove scum that rises to the surface.\r\nIn a separate pan, sauté garlic and onions in oil until translucent.\r\nAdd peanut butter, annatto seeds (soaked in water to extract color), and about 4 cups of the broth from the boiled meats. Stir until well combined.\r\nAdd the peanut sauce to the large pot with the boiled meats. Simmer until the sauce thickens.\r\nAdd eggplants, banana hearts, and string beans. Cook until the vegetables are tender.\r\nSeason with salt and pepper to taste.\r\nServe hot with bagoong (fermented shrimp paste) on the side and steamed rice.', 'https://www.youtube.com/\r\nwatch?v=L_8uVVdaePo&pp\r\n=ygUJS2FyZS1LYXJl '),
('MN-15', 'Beef Kaldereta', 'Kaldereta is a Filipino meat stew known for its rich and flavorful taste. It typically features tender chunks of meat (commonly beef or goat) slow-cooked in a savory tomato-based sauce with vegetables. The dish is often spicy and is a favorite during special occasions and gatherings. Kaldereta, a hearty stew with Spanish origins, demonstrates the Filipino inclination for festive and flavorful meat dishes.', 'Beef, cut into cubes\r\nCooking oil\r\nOnion, chopped\r\nCloves garlic, minced\r\nTomato sauce\r\nLiver spread\r\nGreen olives, sliced\r\nBell peppers, sliced\r\nPotatoes, peeled and sliced\r\nCarrots, peeled and sliced\r\nBeef broth\r\nGrated cheese (optional)\r\nSalt and pepper to taste', 'Protein from Beef: Provides essential amino acids for muscle growth and repair.\r\nVegetables: Carrots and bell peppers offer vitamins and antioxidants.\r\nLiver Spread: Contains iron, vitamin A, and other nutrients.\r\nTomato Sauce: Rich in vitamins C and A, as well as antioxidants like lycopene.\r\nOlives: Good source of healthy fats and antioxidants.\r\nCheese (optional): Provides calcium and protein, but use in moderation due to its fat content.\r\nWhile Kaldereta is a hearty and delicious dish, it\'s important to be mindful of portion sizes and the overall fat content. Adjusting ingredients or using leaner cuts of meat can make it a more health-conscious option.', 'In a large pot, heat oil over medium heat. Sauté garlic and onions until fragrant.\r\nAdd the beef cubes and cook until browned on all sides.\r\nPour in the tomato sauce and liver spread. Mix well.\r\nAdd the beef broth and bring to a boil. Reduce heat to simmer and cover until meat is tender.\r\nAdd potatoes, carrots, olives, and bell peppers. Simmer until vegetables are cooked.\r\nSeason with salt and pepper. Add grated cheese if desired for added richness.\r\nContinue simmering until the sauce thickens.\r\nServe hot with steamed rice.', 'https://www.youtube.com/\r\nwatch?v=rzrjAXluUj4&pp\r\n=ygUOQmVlZiBrYWxkYXJldGE\r\n%3D '),
('MN-16', 'Menudo', 'Menudo is a traditional Filipino stew made with pork, liver, vegetables, and tomato sauce. This hearty dish is known for its rich flavor and is often served during special occasions and celebrations. Menudo is a favorite comfort food that showcases a delightful combination of savory and slightly sweet tastes. The dish mirrors the culinary influence of Spain, showcasing the enduring impact of colonial history.', 'Pork, cubed\r\nPork liver, sliced into strips\r\nOnion, chopped\r\nCloves garlic, minced\r\nPotatoes, peeled and diced\r\nCarrot, peeled and diced\r\nTomato sauce\r\nBeef or pork broth\r\nRed bell pepper, sliced\r\nGreen bell pepper, sliced\r\nRaisins (optional)\r\nSoy sauce\r\nSalt and pepper to taste\r\nCooking oil', 'Protein: Pork and liver are excellent sources of protein, essential for muscle growth and repair.\r\nVegetables: Carrots and bell peppers provide vitamins, minerals, and antioxidants.\r\nTomato Sauce: Rich in lycopene, an antioxidant associated with various health benefits.\r\nSoy Sauce: Adds flavor and contains protein, iron, and other essential nutrients.\r\nGarlic and Onions: Known for their immune-boosting and anti-inflammatory properties.\r\nRaisins: If included, provide natural sweetness and a source of iron and fiber.\r\nMenudo is a nutritious dish that incorporates a variety of ingredients, making it a well-rounded meal. However, it\'s advisable to moderate the intake of certain ingredients, such as liver and soy sauce, especially for individuals with specific dietary considerations. Adjusting the recipe to suit individual preferences and dietary needs is always a good practice.', 'In a pan, heat oil over medium heat. Sauté garlic and onions until aromatic.\r\nAdd pork and cook until browned.\r\nStir in liver and cook for 2-3 minutes.\r\nPour in soy sauce and let it simmer for a few minutes.\r\nAdd tomato sauce and broth. Bring to a boil, then reduce heat to simmer until meat is tender.\r\nAdd potatoes, carrots, bell peppers, and raisins (if using). Simmer until vegetables are cooked.\r\nSeason with salt and pepper to taste.\r\nServe hot with steamed rice.', 'https://www.youtube.com/\r\nwatch?v=HtCLZ4dqrEo&pp\r\n=ygUGTWVudWRv '),
('MN-17', 'Mechado', 'Mechado is a classic Filipino beef stew known for its tender chunks of beef, flavorful tomato-based sauce, and the infusion of soy sauce and citrus. Often cooked with potatoes and carrots, Mechado is a hearty and comforting dish that showcases the rich and diverse flavors of Filipino cuisine. This dish reflects the Spanish-Mexican influence on Filipino cuisine during the colonial period.', 'Beef, cut into cubes\r\nOnion, chopped\r\nCloves garlic, minced\r\nSoy sauce\r\nCalamansi or lemon juice\r\nTomato sauce\r\nBeef broth\r\nPotatoes, peeled and sliced\r\nCarrots, peeled and sliced\r\nRed bell pepper, sliced\r\nBay leaf\r\nSalt and pepper to taste\r\nCooking oil', 'Protein: Beef is a rich source of high-quality protein necessary for muscle development and repair.\r\nVitamins and Minerals: The inclusion of vegetables like potatoes, carrots, and bell peppers provides essential vitamins and minerals.\r\nAntioxidants: Garlic and onions are known for their antioxidant properties, which may contribute to overall health.\r\nCitrus (Calamansi/Lemon): Adds a burst of vitamin C, which is important for immune system function and skin health.\r\nTomato Sauce: Contains lycopene, an antioxidant associated with various health benefits.\r\nWhile Mechado is a nutritious and satisfying dish, moderation is key, especially considering the fat content in beef. Choosing lean cuts of beef and balancing the meal with a variety of vegetables enhances its nutritional profile.', 'In a bowl, marinate the beef in soy sauce and calamansi/lemon juice for about 30 minutes.\r\nIn a large pot, heat oil over medium heat. Sauté garlic and onions until aromatic.\r\nAdd the marinated beef and cook until browned on all sides.\r\nPour in the tomato sauce, beef broth, and add the bay leaf. Bring to a boil, then reduce heat and simmer until the beef is tender.\r\nAdd potatoes, carrots, and red bell pepper. Continue to simmer until the vegetables are cooked.\r\nSeason with salt and pepper to taste.\r\nServe hot over steamed rice.', 'https://www.youtube.com/\r\nwatch?v=GOIlNej0zhQ&pp\r\n=ygUHTWVjaGFkbw%3D%3D'),
('MN-18', 'Afritada', 'Afritada is a traditional Filipino stew known for its combination of meat, vegetables, and a flavorful tomato-based sauce. Typically made with chicken, pork, or beef, Afritada is seasoned with a blend of savory and aromatic ingredients, creating a hearty and comforting dish. This dish highlights the Filipino adaptation of Spanish-inspired culinary techniques, featuring a tomato-based sauce.', 'Chicken, pork, or beef, cut into serving pieces\r\nOnion, peeled and sliced\r\nCloves garlic, minced\r\nPotatoes, peeled and sliced\r\nCarrots, peeled and sliced\r\nBell pepper, sliced\r\nTomato sauce\r\nChicken broth\r\nSoy sauce\r\nFish sauce (patis)\r\nPaprika\r\nSalt and pepper to taste\r\nCooking oil', 'Protein: Depending on the meat used, Afritada provides a good source of high-quality protein.\r\nVegetables: The inclusion of vegetables like potatoes, carrots, and bell peppers adds essential vitamins, minerals, and dietary fiber.\r\nTomato Sauce: Rich in antioxidants, vitamins C and A, and lycopene, which may have health benefits.\r\nGarlic and Onions: Known for their potential immune-boosting and anti-inflammatory properties.\r\nSoy Sauce and Fish Sauce: While adding sodium, these condiments contribute to the savory umami flavor.', 'Heat oil in a pot over medium heat. Sauté garlic and onions until aromatic.\r\nAdd the meat and brown on all sides.\r\nPour in the tomato sauce, chicken broth, soy sauce, fish sauce, and paprika. Stir to combine.\r\nCover the pot and simmer until the meat is tender, adding more broth if needed.\r\nAdd potatoes, carrots, and bell pepper. Cook until vegetables are tender.\r\nSeason with salt and pepper to taste.\r\nServe hot over rice.', 'https://www.youtube.com/\r\nwatch?v=NNvkHkxWd20&pp\r\n=ygUIQWZyaXRhZGE%3D '),
('MN-19', 'Bopis', 'Bopis is a spicy Filipino dish made from minced pork or beef lung and heart, sautéed in a flavorful mixture of tomatoes, onions, garlic, and various spices. Known for its bold and savory taste, Bopis is often enjoyed as a side dish or as a main course served with rice. This dish represents the Filipino love for savory and spicy flavors, influenced by both Spanish and indigenous culinary traditions.', 'Pork or beef lungs, cleaned and finely chopped\r\nPork or beef heart, cleaned and finely chopped\r\nVinegar\r\nSoy sauce\r\nCooking oil\r\nOnion, minced\r\nCloves garlic, minced\r\nTomatoes, diced\r\nRed or green chili peppers, minced\r\nSalt and pepper to taste', 'Protein Source: Bopis provides protein from both pork or beef, essential for muscle development and repair.\r\nIron and Zinc: Organ meats like heart and lungs are rich in iron and zinc, important for blood circulation and immune function.\r\nVitamins: Tomatoes contribute vitamins like C and A, which are beneficial for skin health and immune support.\r\nChili Peppers: Contains capsaicin, known for its potential metabolism-boosting and pain-relief properties.\r\nGarlic: Known for its anti-inflammatory and immune-boosting properties.', 'In a bowl, marinate the chopped pork or beef lungs and heart in vinegar and soy sauce for at least 30 minutes.\r\nHeat oil in a pan over medium heat. Sauté onions and garlic until fragrant.\r\nAdd the marinated pork or beef and cook until browned.\r\nAdd diced tomatoes and cook until softened.\r\nStir in chili peppers and season with salt and pepper to taste.\r\nSimmer until the meat is tender and the flavors are well blended.\r\nServe hot with rice.', 'https://www.youtube.com/\r\nwatch?v=_9weQMu2Kvo&pp\r\n=ygUFQm9waXM%3D '),
('MN-2', 'Lumpiang Togue', 'Lumpiang Togue is a popular Filipino spring roll dish that features mung bean sprouts as a key ingredient. These spring rolls are typically filled with a mixture of vegetables, sometimes including meat or shrimp, and are wrapped in a thin spring roll wrapper. The rolls are then deep-fried until crispy, resulting in a delicious and crunchy appetizer or snack. It showcases the Philippines\' culinary creativity, incorporating locally available ingredients into the traditional spring roll format.', 'Mung bean sprouts\nCarrots, julienned\nTofu or pork, diced (optional)\nGarlic, minced\nOnion, finely chopped\nSpring onions, chopped\nSoy sauce\nFish sauce\nSalt and pepper to taste\nLumpia wrappers (spring roll wrappers)\nCooking oil for frying', 'Rich in Nutrients: Mung bean sprouts are a good source of vitamins, minerals, and antioxidants, providing essential nutrients for overall health.\nLow in Calories: Mung bean sprouts are low in calories, making lumpiang togue a relatively healthy snack or appetizer option.\nVegetable Content: The inclusion of various vegetables in the filling adds fiber, vitamins, and minerals to the dish, contributing to a well-balanced diet.\nProtein Options: Adding tofu or lean pork provides a protein boost, supporting muscle health and helping you feel satiated.\nCustomizable: You can adjust the ingredients to suit your dietary preferences, making it suitable for vegetarian or vegan diets.', 'Prepare the Filling: In a pan, sauté garlic and onions until fragrant. Add tofu or pork (if using) and cook until browned. Add carrots and cook until slightly tender. Incorporate mung bean sprouts and cook briefly. Season with soy sauce, fish sauce, salt, and pepper. Stir in chopped spring onions and cook for a few more minutes. Remove from heat and let the filling cool.\nAssemble the Lumpia: Take a lumpia wrapper and place a portion of the filling in the center. Fold the sides of the wrapper over the filling and roll tightly.\nSeal the Edges: Mix water and flour to create a paste.\nUse this paste to seal the edges of the lumpia wrappers.\nFry the Lumpia: Heat oil in a pan for deep frying. Fry the lumpia until golden brown and crispy. Place on paper towels to drain excess oil.\nServe: Serve the lumpiang togue with a dipping sauce like vinegar with garlic and soy sauce.', 'https://www.youtube.com/\r\nwatch?v=YrgFyn3XFsI'),
('MN-20', 'Bicol Express', 'Bicol Express is a spicy Filipino dish originating from the Bicol region. It features pork cooked in coconut milk, chili peppers, shrimp paste, and various aromatic spices. The dish is known for its rich and creamy texture, coupled with a fiery kick from the chilies, creating a unique and delicious culinary experience. It showcases the culinary distinctiveness of the Bicol region, known for its love of spicy food.', 'Pork belly, sliced into thin strips\r\nCoconut milk\r\nBird\'s eye chili (siling labuyo), chopped (adjust to taste)\r\nOnion, finely chopped\r\nCloves garlic, minced\r\nShrimp paste (bagoong alamang)\r\nCooking oil\r\nSalt and pepper to taste', 'Protein from Pork: Pork provides essential amino acids for muscle development and repair.\r\nCoconut Milk: A good source of healthy fats, vitamins, and minerals. It may boost heart health and improve digestion.\r\nChili Peppers: Contains capsaicin, known for its metabolism-boosting properties and potential pain relief.\r\nOnions and Garlic: Both are rich in antioxidants and have anti-inflammatory properties.\r\nShrimp Paste (Bagoong Alamang): While high in sodium, it adds a unique umami flavor and provides small amounts of protein. ', 'Heat oil in a pan over medium heat. Sauté garlic and onions until fragrant.\r\nAdd pork slices and cook until browned.\r\nStir in shrimp paste and cook for 2 minutes.\r\nPour in coconut milk and bring to a simmer. Allow the pork to cook until tender.\r\nAdd bird\'s eye chili and season with salt and pepper according to taste.\r\nContinue simmering until the coconut milk thickens.\r\nServe hot over steamed rice.', 'https://www.youtube.com/\r\nwatch?v=2ppOMvJqyU8&pp\r\n=ygULQmluYWdvb25nYW4%3D '),
('MN-21', 'Beef Nilaga', 'Beef Nilaga is a traditional Filipino boiled soup dish known for its simplicity and comforting flavors. This clear soup is made with beef shank, bone marrow, and various vegetables. It\'s a popular dish in Filipino households, especially during rainy days or when one seeks a warm and hearty meal. This dish reflects the indigenous Filipino practice of boiling meat with local vegetables, dating back to pre-colonial times.', 'Beef shank, bone marrow included\r\nOnion, peeled and sliced\r\nCloves garlic, minced\r\nCorn on the cob, cut into halves\r\nPotatoes, peeled and quartered\r\nBananas (cooking bananas), peeled and sliced\r\nGreen beans, ends trimmed\r\nCabbage, quartered\r\nSalt and pepper to taste\r\nFish sauce or soy sauce for seasoning\r\nWater for boiling', 'Protein: Beef is an excellent source of high-quality protein, essential for muscle repair and overall body function.\r\nVitamins and Minerals: The vegetables in Beef Nilaga, such as potatoes, corn, and cabbage, contribute essential vitamins and minerals, promoting overall health.\r\nBone Marrow: The bone marrow adds richness to the broth and contains healthy fats, as well as nutrients like iron and vitamin B12.\r\nHydration: The soup base helps keep you hydrated, especially beneficial during illness or in cold weather.\r\nDigestive Health: The combination of vegetables and broth aids in digestion and provides fiber, promoting a healthy digestive system.\r\nRemember, while Beef Nilaga is a nutritious dish, moderation is key, especially for those with specific dietary restrictions. Adjust the recipe according to your taste preferences and dietary needs.', 'Prepare the Beef: In a large pot, place the beef shank and bone marrow. Cover with water and bring to a boil. Skim off any impurities that rise to the surface.\r\nAdd Aromatics: Once the broth is clear, add the sliced onion and minced garlic. Simmer until the beef is tender.\r\nVegetables: Add the corn on the cob, potatoes, saba bananas, and green beans. Season with salt and pepper. Simmer until the vegetables are tender.\r\nCabbage: Lastly, add the cabbage and cook until just wilted. Adjust the seasoning with fish sauce or soy sauce to taste.\r\nServe: Ladle the hot Beef Nilaga into bowls. Serve with steamed rice and enjoy the comforting warmth of this Filipino soup.', 'https://www.youtube.com/\r\nwatch?v=e98fUb1H8Gc&pp\r\n=ygULQmVlZiBOaWxhZ2E%3D '),
('MN-22', 'Pork Sinigang', 'Pork Sinigang is a popular Filipino sour soup known for its distinctive tangy flavor. It features pork, various vegetables, and a tamarind-based broth. This comforting and hearty soup is a staple in Filipino cuisine, enjoyed in households all year round. It embodies the Filipino love for sour flavors and the influence of Southeast Asian culinary traditions.', 'Pork ribs or pork belly, cut into serving pieces\r\nChinese Cabbage\r\nOnion, peeled and quartered\r\nTomatoes, quartered\r\nEggplant, sliced\r\nRadish, peeled and sliced\r\nString beans, cut into 2-inch pieces\r\nGreen chili peppers (siling pansigang)\r\n1 packet (about 40g) sinigang mix (tamarind soup base)\r\nSalt and fish sauce to taste\r\nWater for boiling', 'Rich in Vitamins: Pork Sinigang is loaded with vegetables like eggplant, radish, and string beans, providing essential vitamins and minerals for overall health.\r\nTamarind Benefits: Tamarind, the souring agent in sinigang, is rich in antioxidants and vitamin C. It is known for its potential anti-inflammatory and digestive benefits.\r\nProtein Source: Pork is a good source of protein, necessary for muscle growth and repair.\r\nHydration: The broth in Pork Sinigang contributes to hydration, making it a comforting option during hot weather or when feeling under the weather.\r\nDigestive Aid: The sourness of the tamarind can stimulate digestion, and the vegetables add dietary fiber, promoting a healthy digestive system.\r\nAs with any dish, moderation is key, especially for those with specific dietary concerns. Adjust the recipe to suit your taste preferences and dietary needs.', 'Boil the Pork: In a large pot, place the pork pieces and cover with water. Bring to a boil and skim off any impurities that rise to the surface.\r\nAdd Aromatics: Once the broth is clear, add the quartered onion and tomatoes. Simmer until the pork is tender.\r\nTamarind Soup Base: Add the sinigang mix to the pot. Adjust the sourness to your liking. You can also add fish sauce for additional flavor.\r\nVegetables: Add the sliced chinese cabbage, eggplant, radish, and string beans. Simmer until the vegetables are cooked but not overly soft.\r\nGreen Chili Peppers: Add the green chili peppers for a bit of heat. Adjust the salt and fish sauce according to taste.\r\nServe: Serve the Pork Sinigang hot, ideally with a side of steamed rice. Enjoy the deliciously tangy and savory flavors!', 'https://www.youtube.com/\r\nwatch?v=GS7mJMVZx_I&pp\r\n=ygUNUG9yayBTaW5pZ2FuZw\r\n%3D%3D '),
('MN-23', 'Chicken Tinola', 'Chicken Tinola is a popular Filipino ginger-based soup known for its light and refreshing taste. It typically features chicken pieces, green papaya or chayote, malunggay leaves (moringa), and a ginger-infused broth. This dish is cherished for its simplicity, nourishing qualities, and comforting flavors. It reflects the Filipino preference for light and clear broth soups, influenced by Chinese cooking techniques.', 'Chicken, cut into serving pieces\r\nGreen papaya or chayote, peeled and sliced\r\nGinger, sliced\r\nCloves garlic, minced\r\nOnion, sliced\r\nCooking oil\r\nFish sauce or salt to taste\r\nGround black pepper to taste\r\nMalunggay (moringa) leaves, washed\r\nWater', 'Rich in Protein: Chicken Tinola provides a good source of lean protein from the chicken, essential for muscle development and repair.\r\nImmune-Boosting Ginger: The ginger in the broth is known for its immune-boosting properties and may help alleviate symptoms of the common cold.\r\nVitamins and Minerals: The inclusion of green papaya or chayote and malunggay leaves adds essential vitamins and minerals to the dish, such as vitamin C, potassium, and iron.\r\nHydration: The broth helps keep you hydrated, and the warm soup can be soothing, especially during cold or rainy weather.\r\nDigestive Aid: Ginger is known for its digestive benefits, helping to alleviate nausea and aid in digestion.\r\nChicken Tinola is a nutritious and comforting dish that is commonly enjoyed in Filipino households. As with any recipe, you can adjust the ingredients and seasoning to suit your taste preferences and dietary needs.', 'Sauté Aromatics: In a pot, heat the cooking oil. Sauté ginger, garlic, and onions until fragrant.\r\nAdd Chicken: Add the chicken pieces and cook until lightly browned. Season with fish sauce or salt and ground black pepper.\r\nBoil Chicken: Pour water into the pot and bring it to a boil. Simmer until the chicken is tender, periodically skimming off any impurities that rise to the surface.\r\nAdd Vegetables: Once the chicken is tender, add the green papaya or chayote slices. Cook until the vegetables are tender but not mushy.\r\nAdd Malunggay Leaves: Stir in the malunggay leaves and cook for an additional 2 minutes or until they are wilted.\r\nAdjust Seasoning: Taste the soup and adjust the seasoning with fish sauce or salt and pepper according to your preference.\r\nServe: Serve the Chicken Tinola hot with steamed rice. Enjoy the warm, soothing flavors of this Filipino classic.', 'https://www.youtube.com/\r\nwatch?v=pEMMBceYyMw&pp\r\n=ygUOY2hpY2tlbiB0aW5vbGE\r\n%3D '),
('MN-24', 'Beef Bulalo', 'Beef Bulalo is a Filipino beef shank and marrow bone marrow stew known for its rich and flavorful broth. This dish is characterized by the tender beef shank, bone marrow, and a variety of vegetables. It\'s a comforting and hearty meal often enjoyed in the Philippines, especially during colder weather. It showcases the Filipino affinity for hearty and flavorful beef-based dishes.', 'Beef shank with bone marrow\r\nOnion, peeled and sliced\r\nCloves garlic, minced\r\nCorn on the cob, cut into halves\r\nPotatoes, peeled and quartered\r\nRipe saba bananas (cooking bananas), peeled and sliced\r\nGreen beans, ends trimmed\r\nTaro (gabi), peeled and sliced (optional)\r\nFish sauce or salt to taste\r\nPeppercorns\r\nWater for boiling', 'Nutrient-Rich Broth: The broth, infused with the flavors of beef and bone marrow, is rich in essential nutrients like protein, vitamins, and minerals.\r\nCollagen: The presence of bone marrow in Bulalo contributes collagen, which supports joint health and promotes healthy skin.\r\nVitamins and Minerals: The variety of vegetables provides a spectrum of vitamins and minerals, contributing to overall well-being.\r\nElectrolytes: The broth helps maintain electrolyte balance, making it a good choice for hydration.\r\nImmune Support: The garlic in the recipe contains allicin, which may have immune-boosting properties.\r\nAs with any dish, moderation is important, especially for individuals with specific dietary considerations. Adjust the recipe according to taste preferences and dietary needs. Enjoy Beef Bulalo as a hearty and nourishing meal!', 'Boil the Beef: In a large pot, place the beef shank and bone marrow. Cover with water and bring to a boil. Skim off any impurities that rise to the surface.\r\nAdd Aromatics: Once the broth is clear, add the sliced onion, minced garlic, and peppercorns. Simmer until the beef is tender.\r\nVegetables: Add the corn on the cob, potatoes, saba bananas, green beans, and taro (if using). Season with fish sauce or salt to taste. Simmer until the vegetables are tender.\r\nServe: Ladle the hot Beef Bulalo into bowls. Serve with steamed rice and enjoy the rich and flavorful broth.', 'https://www.youtube.com/\r\nwatch?v=jGM9auGGJLQ&pp\r\n=ygULQmVlZiBCdWxhbG8%3D '),
('MN-25', 'Pancit', 'Pancit is a popular Filipino noodle dish that holds a special place in the country\'s culinary culture. It comes in various regional variations, each with its unique blend of flavors and ingredients. Pancit is often served during celebrations and special occasions, symbolizing longevity and good fortune. It reflects Chinese influence and symbolizes long life and good luck in Filipino culture.', 'Pancit noodles (rice noodles or egg noodles)\r\nCooking oil\r\nOnion, peeled and sliced\r\nCloves garlic, minced\r\nSoy sauce\r\nOyster sauce\r\nChicken broth\r\nCooked chicken, shredded\r\nCooked pork, sliced\r\nShrimp, peeled and deveined\r\nMixed vegetables (carrots, snow peas, cabbage), julienned\r\nGreen onions, chopped\r\nCalamansi, sliced (for serving)', 'Protein: Pancit often contains a variety of meats such as chicken, pork, and shrimp, providing a good source of protein essential for muscle repair and overall body function.\r\nVegetables: The inclusion of vegetables in pancit adds essential vitamins, minerals, and fiber, contributing to overall health and well-being.\r\nCarbohydrates: Noodles are a significant source of carbohydrates, providing energy for daily activities.\r\nBalanced Dish: Pancit is a well-balanced dish that combines proteins, carbohydrates, and vegetables, making it a nutritious option for a satisfying meal.\r\nVersatility: The versatility of pancit allows for customization based on dietary preferences, making it adaptable for various nutritional needs.\r\nAs with any dish, moderation and mindful ingredient choices contribute to a balanced and healthy diet. Adjust the recipe to suit your taste preferences and dietary requirements.', 'Prepare Noodles: Cook the pancit noodles according to package instructions. Drain and set aside.\r\nSauté Aromatics: In a large pan or wok, heat cooking oil over medium-high heat. Sauté onions and garlic until fragrant.\r\nAdd Meat and Seafood: Add the cooked chicken, sliced pork, and shrimp to the pan. Stir-fry until the shrimp turns pink and the meats are heated through.\r\nVegetables: Add the mixed vegetables and continue stir-frying until they are slightly tender yet still crisp.\r\nNoodles and Sauce: Toss in the cooked pancit noodles. Pour soy sauce, oyster sauce, and chicken broth over the noodles. Mix well to ensure even coating.\r\nFinish and Serve: Continue cooking until the noodles have absorbed the flavors and are thoroughly heated. Garnish with chopped green onions and serve with lemon or calamansi slices on the side.', 'https://www.youtube.com/\r\nwatch?v=v3-NsybX4nA&pp\r\n=ygUGUGFuY2l0 '),
('MN-26', 'Mongo', 'Mongo, also known as Mung Bean Soup, is a popular and nutritious dish in Filipino cuisine. It features mung beans, which are small green legumes, cooked into a hearty and flavorful soup with various vegetables and sometimes meat. This dish is well-loved for its comforting taste and versatility. It represents the Filipino penchant for nutritious and hearty soups with a touch of Spanish influence.', 'Mung beans\r\nPork belly or shrimp (optional), sliced into small pieces\r\nOnion, chopped\r\nCloves garlic, minced\r\nTomatoes, chopped\r\nPotato, peeled and diced\r\nCarrot, peeled and diced\r\nSpinach or malunggay leaves\r\nFish sauce or salt to taste\r\nPepper to taste\r\nWater\r\nCooking oil', 'High in Protein: Mung beans are an excellent source of plant-based protein, making this dish suitable for vegetarians and those looking to reduce meat consumption.\r\nRich in Fiber: Mung beans and vegetables contribute fiber to the soup, aiding in digestion and promoting a healthy gut.\r\nVitamins and Minerals: The variety of vegetables in mongo provide essential vitamins and minerals, including vitamin A, vitamin C, potassium, and folate.\r\nLow in Fat: The soup is generally low in fat, especially if prepared without meat or with lean meat options.\r\nAntioxidant Properties: Mung beans contain antioxidants that help neutralize free radicals in the body, supporting overall health.\r\nMongo is not only delicious but also a nutritious option for a well-balanced meal. Adjust the recipe to suit your taste preferences and dietary needs.', 'Prepare the Mung Beans: Rinse the mung beans under cold water and drain.\r\nSaute Aromatics: In a pot, heat cooking oil over medium heat. Saute the garlic, onions, and tomatoes until fragrant and the onions are translucent.\r\nAdd Meat (Optional): If using pork belly or shrimp, add them to the pot and cook until the meat changes color.\r\nAdd Mung Beans: Put the rinsed mung beans into the pot. Stir to combine with the other ingredients.\r\nPour Water: Add water to the pot. Bring it to a boil and then reduce the heat to simmer. Cover and let it cook until the mung beans are tender, stirring occasionally.\r\nAdd Vegetables: Once the mung beans are almost cooked, add the diced potatoes and carrots. Cook until the vegetables are tender.\r\nSeason: Season the soup with fish sauce or salt and pepper according to your taste preferences.\r\nAdd Leafy Greens: Add spinach or malunggay leaves to the pot. Stir and cook until the greens are wilted.\r\nServe: Once everything is cooked through, adjust the seasoning if needed, and serve the mongo hot. It\'s commonly enjoyed with rice.', 'https://www.youtube.com/\r\nwatch?v=IoYRwGJbo4g&pp\r\n=ygUFTW9uZ28%3D '),
('MN-27', 'Pinakbet', 'Pinakbet is a Filipino vegetable stew that hails from the northern regions of the Philippines. Known for its distinct savory flavor, it combines a variety of indigenous vegetables and often includes shrimp paste (bagoong) for a unique umami taste. This dish showcases the rich agricultural diversity of the Philippines and is a staple in Filipino cuisine. It illustrates the integration of indigenous Filipino vegetables and Malay culinary techniques.\n\n', 'Squash, peeled and cubed\r\nOkra, sliced\r\nLong beans (sitaw), cut into 2-inch lengths\r\nEggplant, sliced\r\nBitter melons (ampalaya), sliced\r\nString beans (baguio beans), cut into 2-inch lengths\r\nTomato, sliced\r\nOnion, sliced\r\nCloves garlic, minced\r\nShrimp paste (bagoong)\r\nCooking oil\r\nSalt and pepper to taste\r\nWater for boiling', 'Nutrient-Rich Vegetables: Pinakbet is packed with a variety of vegetables, providing essential vitamins, minerals, and dietary fiber.\r\nAntioxidants: Vegetables like bitter melon and tomatoes are rich in antioxidants, which help combat oxidative stress in the body.\r\nLow in Calories: Pinakbet is a low-calorie dish, making it a healthy option for those watching their calorie intake.\r\nDietary Fiber: The combination of vegetables in Pinakbet contributes to dietary fiber, promoting digestive health.\r\nHeart Health: The use of cooking oil and the absence of heavy meats make Pinakbet a heart-healthy choice when prepared with moderation.\r\nAs with any dish, it\'s essential to balance your diet and adjust recipes according to individual dietary needs and preferences.', 'Prepare Vegetables: Wash and cut all the vegetables into bite-sized pieces.\r\nSaute Aromatics: In a large pan, heat cooking oil over medium heat. Saute garlic until fragrant, then add onions and tomatoes. Cook until the tomatoes are softened.\r\nAdd Vegetables: Add the vegetables one by one, starting with the squash. Stir and saute for a few minutes before adding the next vegetable.\r\nIncorporate Shrimp Paste: Add the shrimp paste (bagoong) to the vegetables. Stir well to distribute the flavors evenly.\r\nSimmer: Pour enough water to cover the vegetables, cover the pan, and let it simmer until the vegetables are tender but not overcooked.\r\nSeason: Season with salt and pepper to taste. Adjust the seasoning as needed.\r\nServe: Once the vegetables are cooked, transfer the Pinakbet to a serving dish. It is typically served with steamed rice. ', 'https://www.youtube.com/\r\nwatch?v=AZT_1WXqKTU&pp\r\n=ygUIUGluYWtiZXQ%3D'),
('MN-28', 'Ginisang Ampalaya', 'Ginisang Ampalaya, also known as Sauteed Bitter Melon, is a popular Filipino dish that transforms the naturally bitter taste of ampalaya (bitter melon) into a flavorful and savory meal. The dish often includes other vegetables and protein, creating a well-balanced and nutritious stir-fry. It highlights the Filipino penchant for balancing flavors and incorporating bitter tastes into their cuisine.', 'Ampalaya (bitter melon), sliced and seeds removed\r\nPork, thinly sliced (optional)\r\nOnion, peeled and sliced\r\nCloves garlic, minced\r\nTomatoes, chopped\r\nEggs, beaten (optional)\r\nSalt and pepper to taste\r\nCooking oil', 'Rich in Nutrients: Ampalaya is a good source of vitamins and minerals, including vitamin C, vitamin A, potassium, and iron.\r\nBlood Sugar Regulation: Ampalaya is known for its potential to help regulate blood sugar levels, making it beneficial for individuals with diabetes.\r\nAntioxidant Properties: The dish is rich in antioxidants, which help combat oxidative stress in the body.\r\nDigestive Health: The fiber in ampalaya supports digestive health and helps prevent constipation.\r\nProtein from Pork and Eggs: If included, pork and eggs contribute protein, essential for muscle development and repair.\r\nGinisang Ampalaya is not only delicious but also offers a range of health benefits, making it a nutritious addition to a balanced diet. Adjust the ingredients and seasoning according to your preferences.', 'Prepare the Ampalaya: Slice the ampalaya in half, lengthwise. Scrape off the seeds and pith using a spoon. Slice the ampalaya into thin crescents.\r\nPrecook the Ampalaya: To reduce bitterness, you can pre-cook the ampalaya slices by blanching them in boiling water for a few minutes. Drain and set aside.\r\nSaute: In a pan, heat cooking oil. Saute onions until translucent, then add minced garlic and cook until aromatic.\r\nAdd Pork (Optional): If using pork, add the thinly sliced pork and cook until browned.\r\nTomatoes: Add chopped tomatoes and cook until softened.\r\nAmpalaya: Add the sliced ampalaya to the pan. Stir-fry until the ampalaya is tender but not overcooked. Season with salt and pepper to taste.\r\nOptional Eggs: Push the ampalaya to the sides of the pan, creating a well in the center. Pour beaten eggs into the well and scramble. Once the eggs are cooked, mix them with the ampalaya.\r\nServe: Transfer the Ginisang Ampalaya to a serving dish. Serve hot with steamed rice.', 'https://www.youtube.com/\r\nwatch?v=XCOUTFwPXV8&pp\r\n=ygURR2luaXNhbmcgQW1w\r\nYWxheWE%3D\r\n');
INSERT INTO `foodinfo` (`foodID`, `foodName`, `foodDescription`, `foodRecipe`, `foodHealthBenefit`, `foodProcedure`, `foodLink`) VALUES
('MN-29', 'Laing', 'Laing is a spicy Filipino dish that originated from the Bicol region. It is made from dried taro leaves cooked in coconut milk and seasoned with chili peppers and other aromatics. This dish is known for its rich and flavorful taste, with a perfect blend of creamy and spicy elements. It showcases the distinct flavors of Bicolano cuisine, featuring spicy and coconut-rich dishes.', 'Dried taro leaves (dried gabi leaves)\r\nBork belly or pork shoulder, sliced thinly\r\nCoconut milk\r\nShrimp, washed\r\nCoconut cream\r\nRed or green chili peppers (siling labuyo), chopped (adjust according to spice preference)\r\nCloves garlic, minced\r\nOnion, sliced\r\nSalt and pepper to taste\r\nCooking oil', 'Health Benefits:\r\nTaro Leaves: Taro leaves are a good source of vitamins A and C, as well as dietary fiber.\r\nCoconut Milk: While high in saturated fats, coconut milk contains medium-chain triglycerides (MCTs), which may have some health benefits.\r\nProtein: The inclusion of pork and dried shrimp adds protein to the dish, essential for muscle health.\r\nChili Peppers: Chili peppers contain capsaicin, which may have metabolism-boosting and pain-relief properties.\r\nDried Shrimp: Dried shrimp provides a concentrated source of umami flavor and adds depth to the dish.\r\nAs with any dish, moderation is key, especially if you have dietary restrictions or health concerns. Adjust the recipe to suit your preferences and dietary needs.', 'Prepare the Dried Taro Leaves: If using dried taro leaves, soak them in warm water for about 30 minutes, then drain.\r\nSaute Aromatics: In a pan, sauté minced garlic and sliced onions in cooking oil until fragrant.\r\nAdd Pork: Add the sliced pork and cook until browned.\r\nAdd Dried Shrimp: Add the washed dried shrimp to the pan and cook for a few minutes until they release their flavor.\r\nAdd Dried Taro Leaves: Put the drained dried taro leaves into the pan and mix well with the other ingredients.\r\nPour Coconut Milk: Pour in the coconut milk and let it simmer over medium heat until the liquid is reduced and the flavors are absorbed by the taro leaves.\r\nAdd Chili Peppers: Add the chopped chili peppers according to your desired level of spiciness. Stir well.\r\nSeasoning: Season with salt and pepper to taste. Adjust the spice level and saltiness according to your preference.\r\nSimmer: Allow the mixture to simmer until the coconut milk is mostly absorbed, and the dish reaches a creamy consistency.\r\nAdd Coconut Cream: Pour coconut cream over the dish and let it simmer for an additional 5-10 minutes until the oil from the coconut cream surfaces.\r\nServe: Laing is best served with steamed rice. Enjoy the rich and spicy flavors!', 'https://www.youtube.com/\r\nwatch?v=sUgwuoiT3RU&pp\r\n=ygUFTGFpbmc%3D '),
('MN-3', 'Lechon Kawali', 'Lechon Kawali is a Filipino dish that features a deep-fried crispy pork belly. It is a popular and festive dish often served during special occasions and celebrations. The pork belly is boiled until tender, then air-dried or refrigerated to achieve a crispy skin when deep-fried. The result is a flavorful and crunchy dish usually served with a side of liver sauce or vinegar dipping sauce. It was introduced during the Spanish colonial period, it has become a staple in Filipino cuisine, symbolizing a fusion of culinary traditions.', 'Pork belly, slab or cut into serving portions\nWater for boiling\nSalt\nPepper\nBay leaves\nOil for deep frying', 'Protein Source: Pork belly is rich in protein, essential for muscle growth, repair, and overall body function.\nVitamins and Minerals: Pork contains various vitamins and minerals, including B vitamins (B12, B6, niacin) and minerals like zinc and phosphorus.\nEnergy Source: The fats in pork belly provide a concentrated source of energy.\nModeration is Key: While Lechon Kawali is a delicious dish, it\'s important to consume it in moderation due to its high fat content. Excessive intake of fried and fatty foods may contribute to health issues such as high cholesterol and cardiovascular issues.\nBalance with Vegetables: Pairing Lechon Kawali with a side of vegetables or a refreshing salad can add fiber, vitamins, and minerals to your meal, promoting a more balanced and nutritious eating experience.', 'Boil the Pork: In a large pot, place the pork belly pieces. Add enough water to cover the meat. Season with salt, pepper, and bay leaves. Boil until the pork is tender. This step can take around 30-45 minutes.\nDry or Refrigerate: Once the pork is tender, remove it from the pot and let it air-dry or refrigerate for several hours or overnight. Air-drying or refrigerating helps remove excess moisture, allowing the skin to crisp up during frying.\nDeep-Fry the Pork: Heat oil in a deep pan or pot for frying. Carefully add the pork belly pieces, skin side down, into the hot oil. Fry until the skin is golden and crispy. Turn the pieces to ensure even frying. Remove from the oil and place on paper towels to drain excess oil.\nSlice and Serve: Once the Lechon Kawali has cooled slightly, slice it into serving portions. Serve with liver sauce or vinegar dipping sauce.', 'https://youtu.be/kFFsm7Wq5kA?si=UO9-ROEV1BWVJCxY'),
('MN-30', 'Adobong Sitaw', 'Adobong Sitaw is a popular Filipino dish featuring string beans (sitaw) cooked in a savory and slightly tangy adobo sauce. This vegetable dish is a flavorful and nutritious addition to Filipino cuisine, showcasing the classic adobo flavors in a meatless version. It represents the Filipino practice of adapting the adobo cooking method to various ingredients.', 'String beans (sitaw), ends trimmed and cut into 2-inch pieces\r\nOnion, peeled and sliced\r\nCloves garlic, minced\r\nCooking oil\r\nSoy sauce\r\nVinegar\r\nBay leaf\r\nPeppercorns\r\nWater\r\nSalt and pepper to taste', 'High in Fiber: String beans are rich in dietary fiber, promoting digestive health and helping to maintain a healthy weight.\r\nVitamins and Minerals: String beans provide essential vitamins such as vitamin C, A, and K, as well as minerals like potassium and folate.\r\nLow in Calories: Adobong Sitaw, being a vegetable dish, is generally low in calories, making it a healthy option for those looking to manage their caloric intake.\r\nHeart Health: The use of soy sauce and vinegar in the adobo sauce provides a savory flavor without relying on excessive salt, contributing to heart health.\r\nVegetarian Option: Adobong Sitaw is a vegetarian dish, making it a great choice for those seeking plant-based or meatless meals.\r\nAs with any dish, moderation and balance are key to a well-rounded and healthy diet. Adjust the recipe to suit your taste preferences and dietary needs.', 'Sauté Aromatics: In a pan, heat cooking oil over medium heat. Sauté garlic until fragrant, then add sliced onions. Cook until onions are translucent.\r\nAdd String Beans: Add the string beans (sitaw) to the pan and stir well with the sautéed aromatics.\r\nAdobo Sauce: Pour in soy sauce and vinegar. Add bay leaf and peppercorns. Stir to combine.\r\nSimmer: Add water to the pan, cover, and let the mixture simmer until the string beans are tender yet still slightly crisp.\r\nAdjust Seasoning: Season with salt and pepper to taste. Adjust the soy sauce and vinegar ratio according to your preference for saltiness and acidity.\r\nServe: Once the string beans are cooked to your liking and the sauce has reduced, remove the bay leaf, and serve the Adobong Sitaw hot over steamed rice.', 'https://www.youtube.com/\r\nwatch?v=47Hms0ayqtU&pp\r\n=ygUNQWRvYm9uZyBTaXRhdw\r\n%3D%3D '),
('MN-31', 'Leche Flan', 'Leche Flan is a popular and delicious Filipino dessert known for its rich and creamy texture. It is a caramel custard made with simple ingredients like eggs, condensed milk, and sugar. The dessert is often served during special occasions and celebrations, making it a staple in Filipino cuisine. It has Spanish origins and is a popular Filipino dessert, reflecting the influence of colonial-era sweets.', 'Egg yolks\r\nCondensed milk\r\nEvaporated milk\r\nSugar (for caramelizing)\r\nVanilla extract (optional)', 'Leche Flan is a dessert that is enjoyed for its taste rather than its nutritional content. While it is rich in calories and sugars, it provides some nutrients from the eggs and dairy products. Eggs are a good source of protein and various vitamins and minerals, including vitamin B12 and selenium. Dairy products contribute to calcium and vitamin D intake, which are essential for bone health.\r\nHowever, it\'s important to consume desserts like Leche Flan in moderation due to their high sugar and calorie content. Individuals with dietary restrictions or health concerns should be mindful of their intake.', 'Caramelizing the Sugar: Place sugar in a saucepan over medium heat. Stir continuously until the sugar melts and turns into a golden caramel color. Quickly pour the caramel into individual llaneras (molds) to coat the bottom evenly.\r\nMaking the Leche Flan Mixture: In a bowl, combine egg yolks, condensed milk, evaporated milk, and vanilla extract (if using). Strain the mixture to achieve a smooth consistency. Gently pour the mixture into the llaneras with caramel.\r\nSteaming or Baking: Cover each llanera with aluminum foil. Steam the llaneras for about 30-40 minutes or until the flan is set. Alternatively, you can bake the llaneras in a water bath in a preheated oven at 350°F (180°C) for about 40-50 minutes.\r\nChilling and Serving: Allow the Leche Flan to cool to room temperature. Refrigerate for at least a few hours or overnight to let it set completely. To serve, run a knife along the edges of the llanera, invert it onto a plate, and let the caramel sauce flow over the Leche Flan.', 'https://www.youtube.com/\r\nwatch?v=6HVDmHRHMOU&pp\r\n=ygUKTGVjaGUgRmxhbg\r\n%3D%3D '),
('MN-32', 'Ginataang Halo-Halo', 'Ginataang Halo-Halo is a traditional Filipino dessert that features a mix of various ingredients cooked in coconut milk. The term \"halo-halo\" translates to \"mix-mix\" in Filipino, reflecting the diverse assortment of ingredients used in this delightful and creamy dessert. It also reflects the Filipino love for coconut-based sweets and the influence of Southeast Asian desserts.', 'Glutinous rice balls (bilo-bilo)\r\nSweet potatoes, peeled and cubed\r\nTaro (gabi), peeled and cubed\r\nRripe plantains (saba), sliced\r\nJackfruit (langka), sliced\r\nTapioca pearls (sago), cooked\r\nCoconut milk\r\nSugar (adjust to taste)\r\nPandan leaf (optional, for flavor)\r\nWater for cooking', 'Ginataang Halo-Halo, like many Filipino desserts, provides a mix of nutrients from its diverse ingredients. Coconut milk, a key component, contains healthy fats and is a source of manganese, copper, and iron. Sweet potatoes and taro contribute dietary fiber, vitamins, and minerals.\r\nHowever, it\'s important to note that this dessert is relatively high in calories and sugars due to the use of coconut milk and sweeteners. As with any sweet treat, moderation is key. Individuals with dietary restrictions or concerns about sugar intake should be mindful of their portions.', 'Preparing the Glutinous Rice Balls (Bilo-Bilo): Mix glutinous rice flour with water to form a dough. Shape the dough into small balls and set aside.\r\nCooking the Ingredients: In a pot, combine coconut milk, water, sweet potatoes, taro, and pandan leaf. Bring the mixture to a boil and simmer until the sweet potatoes and taro are tender. Add the glutinous rice balls, plantains, jackfruit, and sugar. Stir gently.\r\nAdding Tapioca Pearls: Once the glutinous rice balls float to the surface, add the cooked tapioca pearls. Continue to simmer until the rice balls are cooked through.\r\nAdjusting Sweetness: Adjust the sweetness according to your taste preference by adding more sugar if needed. Remove the pandan leaf.\r\nServing: Serve the Ginataang Halo-Halo warm in bowls. Enjoy the creamy and flavorful mix of ingredients.', 'https://www.youtube.com/\r\nwatch?v=hWg8D3KSTyg&pp\r\n=ygUTR2luYXRhYW5nIEhhb\r\nG8gSGFsbw%3D%3D '),
('MN-33', 'Biko', 'Biko is a traditional Filipino rice cake made from glutinous rice, coconut milk, and brown sugar. It is a sweet and sticky delicacy often enjoyed during special occasions and celebrations in Filipino culture. Biko is known for its caramelized topping and chewy texture, making it a popular treat in Filipino cuisine.', 'Glutinous rice\r\nWater (for soaking)\r\nCans (about 800ml) coconut milk\r\nBrown sugar\r\nSalt\r\nBanana leaves (for lining the pan, optional)', 'Biko is a dessert that provides energy from the glutinous rice and coconut milk. Glutinous rice is a good source of carbohydrates, while coconut milk adds flavor and healthy fats to the dish. However, it is important to consume biko in moderation due to its high sugar content from brown sugar and the sticky rice base.\r\nAs with many traditional desserts, biko is enjoyed more for its cultural significance and taste rather than its nutritional profile. Individuals with dietary restrictions or health concerns should be mindful of their intake of sweet treats like biko.', 'Preparing the Glutinous Rice: Rinse the glutinous rice under cold water until the water runs clear. Soak the rice in water for at least 30 minutes to an hour.\r\nCooking the Biko: In a wide pan, combine soaked glutinous rice and coconut milk. Cook over medium heat, stirring constantly until the mixture thickens. Add brown sugar and continue stirring until well combined. Reduce the heat to low and continue cooking until the mixture becomes very thick and sticky. Add salt and mix well.\r\nAssembling and Cooking Biko: Line a baking pan with banana leaves or use parchment paper. Transfer the cooked biko mixture into the lined pan, spreading it evenly. Smooth the top with a spatula.\r\nCaramelizing the Topping: In a separate pan, heat a portion of coconut milk until it thickens and the oil separates. Pour the thickened coconut milk over the top of the biko, spreading it evenly. Using a kitchen torch or by placing it under the broiler for a few minutes, caramelize the coconut milk topping until it turns golden brown.\r\nCooling and Serving: Allow the biko to cool before slicing it into squares or rectangles. Serve at room temperature.', 'https://www.youtube.com/\r\nwatch?v=prwc7f2u6-w&pp\r\n=ygUEQmlrbw%3D%3D '),
('MN-34', 'Kalamay', 'Kalamay is a sweet sticky rice cake that is popular in Filipino cuisine. It is made from glutinous rice, coconut milk, and sugar, creating a dense and chewy texture. Kalamay comes in various forms and flavors, with different regions in the Philippines having their own versions. It is often enjoyed during celebrations and special occasions. It reflects the Filipino penchant for sweets with Chinese and Malay influences.', 'Glutinous rice flour\r\nCoconut milk\r\nBrown sugar\r\nWater\r\nBanana leaves (for lining the mold) or parchment paper', 'Kalamay, like many traditional desserts, is primarily enjoyed for its taste rather than its nutritional content. However, some potential health benefits can be associated with its ingredients. Glutinous rice provides a quick source of energy, while coconut milk contains healthy fats and essential nutrients such as manganese and copper.\r\nIt\'s important to note that kalamay is a sweet and calorie-dense dessert, so moderation is key, especially for individuals with dietary restrictions or health concerns. As with any food, a balanced and varied diet is essential for overall health.', 'Preparing the Banana Leaves: If using banana leaves, cut them into rectangular pieces and pass them over an open flame to make them pliable. Wipe them clean with a damp cloth.\r\nMaking the Kalamay:  In a bowl, combine glutinous rice flour and coconut milk. Mix until smooth and well-blended. In a saucepan, dissolve brown sugar in water over low heat to create a syrup. Once the sugar is completely dissolved, remove from heat. Gradually add the sugar syrup to the rice flour mixture, stirring continuously to avoid lumps.\r\nCooking the Kalamay: Line a mold or baking dish with banana leaves or parchment paper. Pour the kalamay mixture into the mold and smooth the top with a spatula. Steam the kalamay for about 30-40 minutes or until it becomes firm and set.\r\nServing and Storage: Allow the kalamay to cool before slicing into squares or rectangles. Serve at room temperature and enjoy!', 'https://www.youtube.com/\r\nwatch?v=zGgqaneayqQ&pp\r\n=ygURS2FsYW1heSBz\r\nYSBhbGF0aWs%3D'),
('MN-35', 'Bibingka', 'Bibingka is a traditional Filipino rice cake that is often enjoyed during the Christmas season and other special occasions. It is characterized by its unique texture, combining the softness of rice cake with the richness of coconut milk. Bibingka is typically cooked in a special clay pot lined with banana leaves, imparting a distinctive aroma to the cake.', 'Rice flour\r\nAll-purpose flour\r\nBaking powder\r\nSalt\r\nCoconut milk\r\nSugar\r\nEggs\r\nButter, melted\r\nBanana leaves (for lining the pan)\r\nGrated coconut (for topping)\r\nSalted duck eggs, sliced (Optional)\r\nGrated cheese (Optional)\r\nButter (Optional)', 'Bibingka, like many traditional desserts, is primarily enjoyed for its taste rather than its nutritional content. The coconut milk used in the recipe adds a rich flavor and provides some healthy fats. However, it\'s essential to consume rice cakes like bibingka in moderation due to their carbohydrate content.\r\nWhile bibingka may not be a health food, it can be enjoyed as an occasional treat as part of a balanced diet. If you have dietary restrictions or health concerns, it\'s advisable to consult with a healthcare professional for personalized advice.', 'Preparing the Banana Leaves: Pass the banana leaves over an open flame to make them pliable and to enhance their aroma. Cut the banana leaves into circles or squares, depending on the size of your baking pan, and use them to line the bottom and sides of a cake pan.\r\nMaking the Bibingka Batter: In a bowl, combine rice flour, all-purpose flour, baking powder, and salt. Mix well. In a separate bowl, whisk together coconut milk, sugar, eggs, and melted butter until well combined. Gradually add the wet ingredients to the dry ingredients, stirring until a smooth batter is formed.\r\nBaking the Bibingka: Preheat your oven to 375°F (190°C). Pour the bibingka batter into the prepared pan lined with banana leaves. Bake for about 25-30 minutes or until a toothpick inserted into the center comes out clean.\r\nAdding Toppings: Once the bibingka is almost set, add your desired toppings like sliced salted duck eggs, grated cheese, and butter. Continue baking for an additional 10-15 minutes or until the toppings are golden brown.\r\nServing: Allow the bibingka to cool before slicing. Serve it warm and enjoy!', 'https://www.youtube.com/\r\nwatch?v=qFy7WGaDo_8&pp\r\n=ygUIQmliaW5na2E%3D'),
('MN-36', 'Cassava Cake', 'Cassava cake is a popular Filipino dessert made from grated cassava, a starchy root vegetable. The cake is typically sweetened with coconut milk and condensed milk, giving it a rich and creamy texture. It\'s often baked until golden brown, and variations may include toppings like grated cheese or coconut strips. It exemplifies the adaptation of local ingredients into delicious Filipino desserts.', 'Grated cassava (fresh or frozen)\r\nCan (about 14 ounces) condensed milk\r\nCan (about 13.5 ounces) coconut milk\r\nSugar\r\nEggs\r\nButter, melted\r\nGrated cheese (optional, for topping)', 'Cassava itself is a good source of carbohydrates, providing energy for the body. It also contains some fiber, which is beneficial for digestion. However, cassava is low in protein and certain vitamins and minerals, so it\'s important to consume it as part of a balanced diet.\r\nThe addition of coconut milk to cassava cake contributes healthy fats and a distinct flavor. Coconut milk contains medium-chain triglycerides (MCTs), which may offer certain health benefits, including improved heart health. However, it\'s essential to be mindful of portion sizes due to the high calorie and saturated fat content in coconut milk.\r\nAs with any dessert, moderation is key, especially for individuals with dietary restrictions or health concerns.', 'Preparing the Cassava Mixture: In a large mixing bowl, combine grated cassava, condensed milk, coconut milk, sugar, melted butter, and eggs. Mix the ingredients thoroughly until well combined.\r\nBaking: Preheat the oven to 350°F (180°C). Grease a baking dish and pour the cassava mixture into it. Smooth the top with a spatula and bake for about 40-50 minutes or until the top is set and golden brown.\r\nAdding Toppings (Optional): If using grated cheese as a topping, sprinkle it over the cassava cake during the last 10-15 minutes of baking. The cheese should melt and turn golden brown.\r\nCooling and Serving: Allow the cassava cake to cool before slicing it into serving portions. Serve at room temperature.', 'https://www.youtube.com/\r\nwatch?v=XV1NMPNhuOs&pp\r\n=ygUMY2Fzc2F2YSBjYWtl '),
('MN-37', 'Maja Blanca', 'Maja, also known as Maja Blanca, is a traditional Filipino dessert that is both creamy and coconut-flavored. It is a type of coconut pudding made with coconut milk, cornstarch, and sugar. Maja is often garnished with latik, a sweet coconut curd, and toasted coconut flakes. It is a popular choice for celebrations and family gatherings. It reflects the Filipino love for creamy and coconut-flavored sweets, influenced by both indigenous and Spanish desserts.', 'Coconut milk\r\nCornstarch\r\nCup sugar\r\nCan (about 14 ounces) condensed milk\r\nCan (about 12 ounces) evaporated milk\r\nCorn kernels (optional, for added texture)\r\nToasted coconut flakes (for garnish)', 'Maja, like many traditional desserts, is enjoyed for its taste rather than its nutritional content. Coconut milk used in Maja contains healthy fats and provides a distinct flavor. However, it\'s important to consume coconut-based desserts in moderation due to their calorie and saturated fat content.\r\nThe addition of cornstarch and milk products contributes some protein and calcium to the dish. Keep in mind that, like other desserts, Maja is best enjoyed as an occasional treat as part of a balanced diet. Individuals with dietary restrictions or health concerns should be mindful of their overall sugar and calorie intake.', 'Making the Maja Mixture: In a bowl, dissolve cornstarch in a small amount of coconut milk to create a smooth paste. In a saucepan, combine the remaining coconut milk, condensed milk, and evaporated milk. Bring to a gentle simmer over medium heat. Gradually add the sugar, stirring continuously until it dissolves. Slowly whisk in the cornstarch paste, stirring constantly to prevent lumps from forming.\r\nCooking the Maja: Continue cooking the mixture over low to medium heat, stirring continuously until it thickens. If using corn kernels, add them to the mixture and continue stirring until well combined. Once the mixture reaches a thick, pudding-like consistency, pour it into a greased mold or dish.\r\nChilling and Serving: Allow the Maja to cool to room temperature before refrigerating for at least a few hours or until set. Once set, slice into squares or diamonds. Garnish with toasted coconut flakes and latik before serving.', 'https://www.youtube.com/\r\nwatch?v=PDEH-USSy0o&pp\r\n=ygULTWFqYSBCbGFuY2E%3D '),
('MN-38', 'Palitaw', 'Palitaw is a popular Filipino rice cake known for its simplicity and deliciousness. The name \"palitaw\" is derived from the Filipino word \"litaw,\" meaning \"to float\" or \"rise,\" which aptly describes the cooking process. These sweet rice cakes are typically topped with a mixture of grated coconut, sugar, and sesame seeds. It represents a simple yet delightful Filipino kakanin (rice delicacy).', 'Glutinous rice flour\r\nWater\r\nGrated coconut\r\nGranulated sugar\r\nSesame seeds (toasted) for topping', 'Glutinous Rice Flour: While lower in fiber compared to whole grains, glutinous rice flour still provides carbohydrates, which are a source of energy.\r\nCoconut: The grated coconut used in palitaw adds flavor and texture. Coconut contains healthy fats and some essential nutrients, including manganese and copper.\r\nSesame Seeds: Sesame seeds are rich in healthy fats, protein, and various minerals, such as calcium and iron.\r\nDespite these potential benefits, it\'s crucial to consume palitaw in moderation, as it is a sweet treat that may be high in sugar and calories. Individuals with dietary restrictions or health concerns should be mindful of their intake of desserts like palitaw.', 'Making the Palitaw Dough: In a bowl, combine glutinous rice flour and water. Mix until a smooth and sticky dough is formed. Scoop a tablespoon of the dough and shape it into a small, flat disc. Repeat until all the dough is used.\r\nCooking the Palitaw: Bring a pot of water to a boil. Drop the shaped dough discs into the boiling water. They are ready when they float to the surface. Using a slotted spoon, carefully remove the floating palitaw and place them on a plate.\r\nCoating and Topping: Roll each palitaw in grated coconut until well-coated. In a separate bowl, mix sugar and toasted sesame seeds. Dip the coated palitaw in the sugar and sesame seed mixture, ensuring they are evenly covered.', 'https://www.youtube.com/\r\nwatch?v=GoK3GgqS9Ms&pp\r\n=ygUHUGFsaXRhdw%3D%3D '),
('MN-39', 'Puto', 'Puto is a traditional Filipino steamed rice cake that is a popular snack or breakfast item. It is known for its soft and fluffy texture, and mildly sweet taste, and is often served with various savory or sweet accompaniments. Puto comes in different colors and flavors, making it a versatile and beloved treat in Filipino cuisine. It has Chinese origins and is a staple in Filipino celebrations, showcasing the influence of early Chinese traders.', 'Rice flour\r\nAll-purpose flour\r\nCoconut milk\r\nSugar\r\nBaking powder\r\nSalt\r\nWater (adjust as needed for consistency)\r\nCheese, salted egg, or grated coconut for toppings (Optional)', 'While puto is primarily enjoyed for its taste and cultural significance, it provides some nutritional value, especially when made with ingredients like rice flour and coconut milk. Rice flour is gluten-free and a good source of energy. Coconut milk adds a rich flavor and provides healthy fats, vitamins, and minerals.\r\nIt\'s important to note that puto, like many traditional desserts, is often a treat rather than a health food. Moderation is key, especially for individuals with dietary restrictions or health concerns related to sugar and calorie intake. Additionally, variations in recipes may affect the nutritional content of puto.', 'In a large mixing bowl, combine rice flour, all-purpose flour, sugar, baking powder, and salt. Mix well.\r\nGradually add coconut milk while continuously stirring to avoid lumps.\r\nAdd water and mix until you achieve a smooth batter consistency. Adjust the water if needed.\r\nFill each puto mold about 2/3 full with the batter.\r\nSteam the puto over boiling water for about 15-20 minutes or until a toothpick inserted in the center comes out clean.\r\nOptional: Add cheese, salted egg, or grated coconut on top of each puto before steaming for added flavor and texture.\r\nAllow the puto to cool before removing them from the molds.\r\nServe and enjoy the puto on its own or with your choice of accompaniment.', 'https://www.youtube.com/\r\nwatch?v=6fZkPa4MQQ0&pp\r\n=ygUEUHV0bw%3D%3D '),
('MN-4', 'Crispy Pata', 'Crispy Pata is a popular Filipino dish known for its indulgent and flavorful preparation of deep-fried pork leg. The dish is characterized by its crispy and golden-brown skin, while the meat inside remains tender and succulent. It\'s often served with a dipping sauce and is a favorite during special occasions and celebrations in Filipino cuisine. It highlights the Filipinos\' love for crispy and savory meat.', 'Whole pork leg (pata)\r\nWater for boiling\r\nSalt\r\nPepper\r\nBaking soda (optional)\r\nSoy sauce\r\nFish sauce\r\nGarlic, minced\r\nBay leaves\r\nOil for deep frying', 'Protein Source: Pork is a good source of protein, essential for muscle growth and repair.\r\nRich in Nutrients: Pork leg contains essential nutrients like vitamins (B vitamins, particularly) and minerals (such as iron and zinc).\r\nCaloric Energy: While crispy pata is a flavorful dish, it is also high in calories and fat. Moderation is key, especially for individuals watching their calorie and fat intake.\r\nCollagen Content: The cooking process of boiling followed by deep-frying may contribute to the extraction of collagen from the pork skin, which is known to have potential benefits for skin health.', 'Prepare the Pork Leg: Clean the pork leg thoroughly. Place the pork leg in a large pot and add enough water to cover it. Add salt, pepper, and baking soda (optional) to the water. Boil the pork leg until it becomes tender. This can take several hours, depending on the size and thickness of the pork leg.\r\nMarinate the Pork Leg: Once the pork leg is tender, remove it from the pot and let it cool. Rub the pork leg with soy sauce, fish sauce, minced garlic, and pepper. Allow it to marinate for at least 30 minutes to absorb the flavors.\r\nDeep-Fry the Pork Leg: Heat oil in a deep fryer or a large, deep pan.\r\nCarefully lower the marinated pork leg into the hot oil and deep-fry until the skin becomes crispy and golden brown. Ensure that the pork leg is cooked through and reaches an internal temperature that is safe for consumption.\r\nServe: Remove the crispy pata from the oil and let it drain on paper towels.\r\nServe the crispy pata hot and crispy, accompanied by a dipping sauce such as soy sauce with calamansi (Filipino lime) and minced garlic.', 'https://www.youtube.com/\r\nwatch?v=CRNg_2LudHA '),
('MN-40', 'Turon', 'Turon, also known as banana lumpia or banana spring rolls, is a popular Filipino snack or dessert. It is made by wrapping slices of ripe banana and occasionally jackfruit in a spring roll wrapper, then frying until crispy. The roll is coated with caramelized sugar, giving it a sweet and crunchy exterior. It reflects the Filipino love for combining sweet and savory flavors in snacks and desserts.', 'Ripe bananas (saba variety is commonly used)\r\nJackfruit slices (optional)\r\nLumpia/spring roll wrappers\r\nBrown sugar\r\nCooking oil for frying', 'Bananas: Rich in potassium, vitamins (such as vitamin C and vitamin B6), and dietary fiber. Bananas are a natural source of energy.\r\nJackfruit: Contains various nutrients, including vitamin C, potassium, and dietary fiber. It is also known for its antioxidant properties.\r\nDietary Fiber: The fruits and wrappers used in turon contribute to dietary fiber, which is essential for digestive health.\r\nDespite these benefits, turon is typically fried and coated in sugar, which increases its calorie and sugar content. As with any sweet or fried treat, moderation is key. It\'s important to enjoy turon as part of a balanced diet and not as a primary source of nutrition.', 'Prepare the Banana and Jackfruit: Peel and slice the bananas lengthwise. If using jackfruit, cut it into thin strips.\r\nCoat with Sugar: Roll each banana slice in brown sugar, ensuring an even coating.\r\nAssemble the Turon: Place a banana slice (coated in sugar) and jackfruit strip on a lumpia wrapper. Roll the wrapper tightly, sealing the edges with water.\r\nFry the Turon: Heat cooking oil in a pan for deep frying. Fry the turon until golden brown and crispy. Remove excess oil by placing the fried turon on paper towels.\r\nServe: Let the turon cool for a few minutes before serving. Enjoy the crispy and sweet treat!', 'https://www.youtube.com/\r\nwatch?v=4QeQ4O6WHkc&pp\r\n=ygUFVHVyb24%3D '),
('MN-5', 'Liempo', 'Liempo is a popular Filipino dish consisting of marinated and grilled pork belly. Known for its savory and flavorful taste, liempo is often enjoyed as a main dish or as part of a barbecue feast. The pork belly is typically seasoned with a mixture of garlic, soy sauce, and other spices, giving it a deliciously charred and smoky flavor. The dish showcases the influence of Spanish-style barbecue, introduced during the colonial period, adapted to local tastes.', 'Pork belly, slab or sliced\r\nGarlic, minced\r\nSoy sauce\r\nCalamansi or lemon juice\r\nGround black pepper\r\nSalt\r\nBrown sugar (optional)\r\nCooking oil for grilling', 'Protein Source: Pork belly is a good source of protein, essential for muscle growth, repair, and overall body function.\r\nRich in Nutrients: Pork belly contains essential nutrients like B vitamins (B12, B6, niacin) and minerals (iron, zinc) that play crucial roles in various bodily functions.\r\nEnergy Source: The fat content in pork belly provides a concentrated source of energy, though it\'s essential to consume it in moderation as part of a balanced diet.\r\nCollagen: Pork belly contains collagen, which is beneficial for skin health and can support joint health.\r\nCustomizable Marinade: You can control the ingredients in the marinade, making it adaptable to different dietary preferences and flavor profiles.', 'Prepare the Marinade: In a bowl, mix minced garlic, soy sauce, calamansi or lemon juice, ground black pepper, and a pinch of salt. Optionally, add brown sugar for a hint of sweetness.\r\nMarinate the Pork Belly: Coat the pork belly thoroughly with the marinade.\r\nAllow the pork to marinate for at least a few hours or overnight in the refrigerator for better flavor absorption.\r\nPreheat the Grill: Preheat your grill to medium-high heat.\r\nGrill the Pork Belly: Brush the grill grates with cooking oil to prevent sticking.\r\nPlace the marinated pork belly on the grill and cook each side until it develops a nice char and is fully cooked through. Baste the pork belly with the remaining marinade while grilling to enhance flavor.\r\nServe: Once cooked, transfer the liempo to a serving plate.\r\nSlice the pork belly into serving portions.\r\nOptional Dipping Sauce: Prepare a dipping sauce using soy sauce, calamansi or lemon juice, and minced garlic for added flavor.', 'https://www.youtube.com/\r\nwatch?v=1402LmORS54'),
('MN-6', 'Pritong Manok', 'Pritong Manok is a popular Filipino dish that features crispy and flavorful fried chicken. Marinated with a blend of spices, the chicken is deep-fried until golden brown, resulting in a delicious and crunchy outer layer while keeping the inside tender and juicy. It is a universal comfort food found in various cultures. In the Filipino context, it represents the global influence on local cuisine, becoming a popular fast-food item and family meal.', 'Chicken pieces (drumsticks, wings, thighs, or a whole chicken, depending on preference)\r\nSoy sauce\r\nFish sauce\r\nGarlic, minced\r\nGinger, grated\r\nSalt and pepper to taste\r\nAll-purpose flour\r\nCooking oil for frying', 'Protein Source: Chicken is an excellent source of lean protein, supporting muscle development and repair.\r\nEssential Nutrients: Chicken provides essential nutrients such as vitamins B6 and B12, which are important for energy metabolism and neurological health.\r\nVersatile Dish: Pritong Manok can be customized by adjusting the marinade ingredients, making it suitable for various flavor preferences.\r\nModeration: While fried, enjoying Pritong Manok in moderation can be part of a balanced diet. Opting for lean cuts and practicing portion control helps manage calorie intake.\r\nHome Cooking Control: Cooking at home allows you to control the ingredients and cooking methods, reducing the use of excessive oil and additives often found in commercial fried chicken.', 'Marinate the Chicken: In a bowl, mix soy sauce, fish sauce, minced garlic, grated ginger, salt, and pepper to create the marinade. Coat the chicken pieces with the marinade, ensuring they are well-covered. Allow the chicken to marinate for at least 30 minutes to enhance flavor.\r\nCoat with Flour: Roll each marinated chicken piece in all-purpose flour, making sure they are evenly coated. This helps achieve a crispy outer layer when fried.\r\nHeat Oil for Frying: In a deep fryer or a large, deep pan, heat cooking oil to a temperature suitable for frying (around 350-375°F or 175-190°C).\r\nFry the Chicken: Carefully place the coated chicken pieces into the hot oil, ensuring not to overcrowd the pan. Fry until the chicken is golden brown and the internal temperature reaches at least 165°F (74°C). Drain excess oil by placing the fried chicken on paper towels.\r\nServe: Pritong Manok is typically served hot and crispy, often with a side of rice or your favorite dipping sauce.', 'https://www.youtube.com/\r\nwatch?v=6zHR1ABP7N0&pp\r\n=ygUNUHJpdG9uZyBNYW5vaw\r\n%3D%3D '),
('MN-7', 'Daing na Bangus', 'Daing na Bangus is a traditional Filipino dish that features milkfish marinated in a mixture of vinegar, garlic, and spices, then sun-dried before being pan-fried or grilled. The result is a flavorful and savory dish with a unique combination of tanginess and richness, showcasing the delicious taste of the milkfish. It showcases indigenous Filipino culinary practices that have withstood the test of time.', 'Milkfish (Bangus), cleaned and butterflied\r\nVinegar\r\nGarlic, minced\r\nPeppercorns\r\nSalt\r\nCooking oil for frying', 'Rich in Omega-3 Fatty Acids: Milkfish is a good source of omega-3 fatty acids, which are essential for heart health and may help reduce inflammation.\r\nProtein: Daing na Bangus is a protein-rich dish, supporting muscle development, repair, and overall body function.\r\nVitamins and Minerals: Milkfish contains essential vitamins and minerals such as vitamin D, vitamin B12, and selenium, contributing to bone health and overall well-being.\r\nGarlic Benefits: Garlic, a key ingredient in the marinade, is known for its potential health benefits, including anti-inflammatory and antibacterial properties.\r\nLow in Carbohydrates: This dish is low in carbohydrates, making it a suitable option for those managing their carbohydrate intake.', 'Prepare the Marinade: In a bowl, combine vinegar, minced garlic, peppercorns, and salt to create the marinade. Adjust the quantities according to your taste preferences.\r\nMarinate the Milkfish: Place the cleaned and butterflied milkfish in a shallow dish. Pour the marinade over the fish, making sure it is well-coated. Marinate for at least 30 minutes to allow the flavors to infuse.\r\nSun-Dry the Marinated Milkfish: After marinating, allow the milkfish to sun-dry for several hours. This step helps intensify the flavors and aids in preserving the fish.\r\nFry the Daing na Bangus: Heat cooking oil in a pan for frying. Fry the marinated and sun-dried milkfish until both sides are golden brown and crispy. Remove excess oil by placing the fried fish on paper towels.\r\nServe: Daing na Bangus is commonly served with rice and a side of vinegar dipping sauce with crushed garlic and soy sauce.', 'https://www.youtube.com/\r\nwatch?v=IExcg8ZxLuA&pp=\r\nygUPRGFpbmcgbmEgQmFuZ3Vz '),
('MN-8', 'Pinalamanan na Bangus', 'Pinalamanan na Bangus is a traditional Filipino dish that features milkfish (bangus) stuffed with a flavorful mixture of vegetables and sometimes ground meat. The dish is typically marinated, then deep-fried until the fish is golden brown and crispy. Pinalamanan na Bangus is known for its delicious combination of textures and savory flavors. It reflects a blend of Spanish and indigenous Filipino culinary traditions. Stuffed with various ingredients, it highlights the adaptability of Filipino cuisine.', 'Whole milkfish (bangus), scaled and cleaned\r\nGarlic, minced\r\nOnion, finely chopped\r\nTomatoes, diced\r\nGreen bell pepper, diced\r\nCarrots, julienned\r\nRaisins (optional)\r\nGreen peas (optional)\r\nSoy sauce\r\nFish sauce\r\nSalt and pepper to taste\r\nCooking oil for frying', 'Rich in Omega-3 Fatty Acids: Milkfish is a good source of omega-3 fatty acids, which are beneficial for heart health and can help reduce inflammation.\r\nProtein: Milkfish provides a high-quality source of protein, essential for muscle growth, repair, and overall body function.\r\nVitamins and Minerals: The vegetables in the stuffing contribute to the dish\'s nutritional value, providing essential vitamins and minerals.\r\nCustomizable: You can adjust the stuffing ingredients to include more vegetables or lean meat, making it a versatile dish that suits various dietary preferences.\r\nCooking Method: While deep-frying adds a crispy texture, the dish can be modified by choosing alternative cooking methods like grilling or baking for a lighter option.', 'Prepare the Milkfish: Clean the milkfish thoroughly, removing scales and innards. Make a long slit along the back of the fish, creating a pocket for the stuffing.\r\nPrepare the Stuffing: In a pan, sauté garlic and onions until fragrant. Add tomatoes, bell pepper, carrots, raisins, and green peas (if using). Season with soy sauce, fish sauce, salt, and pepper. Cook until the vegetables are slightly tender. Let the stuffing mixture cool.\r\nStuff the Milkfish: Carefully stuff the prepared mixture into the pocket of the milkfish. Sew or use toothpicks to secure the opening.\r\nMarinate: Marinate the stuffed milkfish in a mixture of soy sauce, fish sauce, and minced garlic for at least an hour.\r\nDeep-Fry: Heat cooking oil in a deep pan or wok for frying. Gently place the stuffed milkfish into the hot oil. Fry until golden brown on both sides.\r\nServe: Remove excess oil by placing the fried stuffed milkfish on paper towels. Slice and serve with your favorite dipping sauce.', 'https://www.youtube.com/watch\r\n?v=7sI8uAfsxlY&pp=ygUScGlu\r\nYWxhbWFuYW4gYmFuZ3Vz '),
('MN-9', 'Calamares', 'Calamares is a Filipino dish that features crispy and seasoned squid rings, deep-fried to perfection. It is a popular street food and appetizer in the Philippines, known for its delicious taste and crunchy texture. Often served with a side of vinegar-based dipping sauce, kalamares is a favorite among those who enjoy seafood. It reflects the maritime influences in Filipino cuisine. It showcases the abundance of seafood in the Philippines and the influence of global flavors in local dishes.', 'Squid, cleaned and sliced into rings\r\nAll-purpose flour\r\nCornstarch\r\nBaking powder\r\nSalt and pepper to taste\r\nGarlic powder\r\nOnion powder\r\nEggs, beaten\r\nCooking oil for deep frying', 'Rich in Protein: Squid is a good source of high-quality protein, essential for building and repairing tissues in the body.\r\nNutrient Content: Squid contains vitamins and minerals such as B vitamins (B12, B6, niacin), phosphorus, and selenium, contributing to overall health.\r\nLow in Calories: When prepared without excessive breading or frying, kalamares can be a relatively low-calorie seafood option.\r\nOmega-3 Fatty Acids: Squid is a source of omega-3 fatty acids, which are beneficial for heart health and may help reduce inflammation.\r\nVersatility: The basic nature of kalamares allows for customization in terms of seasonings and coatings, making it adaptable to personal taste preferences and dietary needs.', 'Prepare the Squid: Clean the squid thoroughly and slice it into rings. Pat them dry with paper towels.\r\nCreate the Coating Mixture: In a bowl, combine all-purpose flour, cornstarch, baking powder, salt, pepper, garlic powder, onion powder, and paprika (if using). Mix well.\r\nCoat the Squid: Dip the squid rings into the beaten eggs, ensuring they are fully coated. Dredge the squid rings in the flour mixture, covering them evenly.\r\nHeat the Oil: In a deep fryer or a deep pan, heat cooking oil to around 350-375°F (175-190°C).\r\nFry the Squid Rings: Carefully place the coated squid rings into the hot oil, a few at a time, to avoid overcrowding. Fry until they turn golden brown and crispy, usually for about 2-3 minutes per batch.\r\nDrain and Serve: Use a slotted spoon to remove the fried squid rings from the oil and place them on a plate lined with paper towels to absorb excess oil.\r\nServe with Dipping Sauce: Serve kalamares hot with a side of vinegar-based dipping sauce, often mixed with garlic, soy sauce, and pepper.', 'https://www.youtube.com/\r\nwatch?v=bCUsNOTfxIU&pp\r\n=ygUJY2FsYW1hcmVz ');

-- --------------------------------------------------------

--
-- Table structure for table `userinfo`
--

CREATE TABLE `userinfo` (
  `userFirstName` varchar(100) NOT NULL,
  `userLastName` varchar(100) NOT NULL,
  `userName` varchar(100) NOT NULL,
  `userEmail` varchar(100) NOT NULL,
  `userPassword` varchar(100) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `userinfo`
--

INSERT INTO `userinfo` (`userFirstName`, `userLastName`, `userName`, `userEmail`, `userPassword`) VALUES
('Keano', 'Salvador', 'keano321', 'keano@gmail.com', 'keano321#@!'),
('Kyla Gissele', 'Trinidad', 'Kyla789', 'kyla@gmail.com', 'kyla789G&*('),
('Leslie Charm', 'Cadduan', 'Leslie456', 'leslie@gmail.com', '$%^456leslie'),
('Marjorie', 'Reminal', 'marj098', 'marj@gmail.com', 'marj)*(098'),
('Romar ', 'Malirong', 'Romar890', 'romar@gmail.com', 'romar*(890)'),
('Shania', 'Dar', 'shania123', 'shania@gmail.com', 'SD123!@#');

-- --------------------------------------------------------

--
-- Table structure for table `usermessage`
--

CREATE TABLE `usermessage` (
  `commentNum` int(11) NOT NULL,
  `userName` varchar(100) NOT NULL,
  `userComment` text NOT NULL,
  `commentTime` datetime NOT NULL DEFAULT current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `usermessage`
--

INSERT INTO `usermessage` (`commentNum`, `userName`, `userComment`, `commentTime`) VALUES
(35, 'keano321', 'Hello World!', '2023-12-17 20:20:53'),
(37, 'Kyla789', 'ABCDEFGHIJKLMNOPQRSTUVWXYZ', '2023-12-17 20:22:35'),
(39, 'marj098', 'Happy Birthday!', '2023-12-17 20:25:40'),
(40, 'romar890', 'Happy New Year!', '2023-12-17 20:28:56'),
(41, 'shania123', 'Merry Christmas and Happy New Year!!!', '2023-12-17 20:30:06'),
(48, 'Leslie456', 'WAWAWAWAWAWAWAW', '2023-12-18 23:01:55');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `admininfo`
--
ALTER TABLE `admininfo`
  ADD PRIMARY KEY (`adminID`);

--
-- Indexes for table `foodinfo`
--
ALTER TABLE `foodinfo`
  ADD PRIMARY KEY (`foodID`);

--
-- Indexes for table `userinfo`
--
ALTER TABLE `userinfo`
  ADD PRIMARY KEY (`userName`);

--
-- Indexes for table `usermessage`
--
ALTER TABLE `usermessage`
  ADD PRIMARY KEY (`commentNum`),
  ADD KEY `userName` (`userName`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `usermessage`
--
ALTER TABLE `usermessage`
  MODIFY `commentNum` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=58;

--
-- Constraints for dumped tables
--

--
-- Constraints for table `usermessage`
--
ALTER TABLE `usermessage`
  ADD CONSTRAINT `usermessage_ibfk_1` FOREIGN KEY (`userName`) REFERENCES `userinfo` (`userName`) ON DELETE CASCADE ON UPDATE CASCADE;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
